### ISSUE TITLE
Missing arrow/chevron

### ISSUE THREAD

**Issue by barydos** [martinkorelic/joplin-plugin-spoilers#5]
![image](https://user-images.githubusercontent.com/41723598/139650338-752f789e-e966-45e3-9a6f-a6be0cc7449e.png)

This is what it looks like on my system. Is there perhaps something I'm missing?
Fortunately, the spoiler _functionality_ works properly - and this box like symbol will also rotate as the spoiler is displayed.

Thanks

--
Joplin 2.3.5 (prod, linux)

**Comment by martinkorelic** [comment]
Not sure why this is not working, could be a system problem not recognizing the correct symbol.
But you can change it into something custom using `userstyle.css`.
```css
/* Container for spoiler title */
  .summary-title:before {
    content: "Something custom";
  }
```
